version: '3.9'
services:
  app:
    ports:
      - 8080:80
    image: maolanaikhsan31/app-nisan:v1
    networks:
      - nisan
    deploy:
      replicas: 4
      placement:
        constraints: [node.role == worker]
      update_config:
        delay: 5s
      restart_policy:
        condition: on-failure

  db:
    image: maolanaikhsan31/mariadb:10.7.8
    volumes:
       - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: "db_toko"
    secrets:
      - mysql_root_password
    networks:
      - nisan
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == worker]
      update_config:
        delay: 5s
      restart_policy:
        condition: on-failure

  lb:
    ports:
      - 80:80
      - 8404:8404
    image: maolanaikhsan31/haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    dns: 127.0.0.11
    networks:
      - nisan
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 5s

secrets:
  mysql_root_password:
    external: true

networks:
  nisan:
    driver: overlay

volumes:
  db_data:
